
apiVersion: v1
kind: Service
metadata:
  name: addition-service
spec:
  selector:
    app: addition-service
  ports:
    - name: addition-port
      protocol: TCP
      port: 81
      targetPort: 8081
  type: LoadBalancer
