
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: addition-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: addition-service
  endpoints:
  - port: addition-port
