
openapi: 3.0.0
info:
  title: Addition API
  version: 1.0.0

paths:
  /add:
    post:
      summary: Add two numbers
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                num1:
                  type: integer
                num2:
                  type: integer
      responses:
        '200':
          description: Successful addition
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: integer
