apiVersion: v1
kind: Service
metadata:
  name: service-1-service
spec:
  selector:
    app: login-service
  ports:
    - name: login-port
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer