apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      containers:
      - name: login-service
        image: starian/login-service
        ports:
        - containerPort: 8080