apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: login-service-monitor
  namespace: default
  labels:
    app: login-service
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: login-service
  endpoints:
  - port: http
    interval: 5s