from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class LoginPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, username=None, password=None):  # noqa: E501
        """LoginPostRequest - a model defined in OpenAPI

        :param username: The username of this LoginPostRequest.  # noqa: E501
        :type username: str
        :param password: The password of this LoginPostRequest.  # noqa: E501
        :type password: str
        """
        self.openapi_types = {
            'username': str,
            'password': str
        }

        self.attribute_map = {
            'username': 'username',
            'password': 'password'
        }

        self._username = username
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'LoginPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _login_post_request of this LoginPostRequest.  # noqa: E501
        :rtype: LoginPostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this LoginPostRequest.


        :return: The username of this LoginPostRequest.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this LoginPostRequest.


        :param username: The username of this LoginPostRequest.
        :type username: str
        """

        self._username = username

    @property
    def password(self) -> str:
        """Gets the password of this LoginPostRequest.


        :return: The password of this LoginPostRequest.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this LoginPostRequest.


        :param password: The password of this LoginPostRequest.
        :type password: str
        """

        self._password = password
