from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class LoginPost200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, token=None):  # noqa: E501
        """LoginPost200Response - a model defined in OpenAPI

        :param token: The token of this LoginPost200Response.  # noqa: E501
        :type token: str
        """
        self.openapi_types = {
            'token': str
        }

        self.attribute_map = {
            'token': 'token'
        }

        self._token = token

    @classmethod
    def from_dict(cls, dikt) -> 'LoginPost200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _login_post_200_response of this LoginPost200Response.  # noqa: E501
        :rtype: LoginPost200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self) -> str:
        """Gets the token of this LoginPost200Response.


        :return: The token of this LoginPost200Response.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this LoginPost200Response.


        :param token: The token of this LoginPost200Response.
        :type token: str
        """

        self._token = token
