from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class PasswordResetPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, email=None):  # noqa: E501
        """PasswordResetPostRequest - a model defined in OpenAPI

        :param email: The email of this PasswordResetPostRequest.  # noqa: E501
        :type email: str
        """
        self.openapi_types = {
            'email': str
        }

        self.attribute_map = {
            'email': 'email'
        }

        self._email = email

    @classmethod
    def from_dict(cls, dikt) -> 'PasswordResetPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _password_reset_post_request of this PasswordResetPostRequest.  # noqa: E501
        :rtype: PasswordResetPostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email(self) -> str:
        """Gets the email of this PasswordResetPostRequest.


        :return: The email of this PasswordResetPostRequest.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this PasswordResetPostRequest.


        :param email: The email of this PasswordResetPostRequest.
        :type email: str
        """

        self._email = email
