from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class RegisterPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, username=None, password=None, email=None):  # noqa: E501
        """RegisterPostRequest - a model defined in OpenAPI

        :param username: The username of this RegisterPostRequest.  # noqa: E501
        :type username: str
        :param password: The password of this RegisterPostRequest.  # noqa: E501
        :type password: str
        :param email: The email of this RegisterPostRequest.  # noqa: E501
        :type email: str
        """
        self.openapi_types = {
            'username': str,
            'password': str,
            'email': str
        }

        self.attribute_map = {
            'username': 'username',
            'password': 'password',
            'email': 'email'
        }

        self._username = username
        self._password = password
        self._email = email

    @classmethod
    def from_dict(cls, dikt) -> 'RegisterPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _register_post_request of this RegisterPostRequest.  # noqa: E501
        :rtype: RegisterPostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this RegisterPostRequest.


        :return: The username of this RegisterPostRequest.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this RegisterPostRequest.


        :param username: The username of this RegisterPostRequest.
        :type username: str
        """

        self._username = username

    @property
    def password(self) -> str:
        """Gets the password of this RegisterPostRequest.


        :return: The password of this RegisterPostRequest.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this RegisterPostRequest.


        :param password: The password of this RegisterPostRequest.
        :type password: str
        """

        self._password = password

    @property
    def email(self) -> str:
        """Gets the email of this RegisterPostRequest.


        :return: The email of this RegisterPostRequest.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this RegisterPostRequest.


        :param email: The email of this RegisterPostRequest.
        :type email: str
        """

        self._email = email
